---
# Create VLB
- hosts: all
  connection: local
  gather_facts: False

  vars_files:
  - pri_vars/all

  tasks:
  - name: Gather ec2 facts
    ec2_facts:  

  - name: Add hosts to ELB
    local_action:
      module: ec2_elb
      state: present
      region: "{{ ec2_region }}"
      ec2_elbs: demo-elb
      instance_id: "{{ item }}"
    with_items:
      - i-52df4077 
      - i-fe22bedb


#      listeners:
#        - protocol=http
#          load_balancer_port=80
#          instance_port=8080
