---
- name: terminate hosts
  hosts: all

  vars:
   ec2_region: "us-east-1"
   ec2_instance_ids: []

  tasks:
  - name: terminate EC2 hosts
    ec2: >
      region="{{ ec2_region }}"
      instance_ids="{{ item }}"
      state=absent
      wait=True
    with_items: ec2_instance_ids:
