---
- name: Terminate AWS Hosts
  hosts: all

  vars:
    ec2_region: us-east-1

  tasks:
  - name: Destroy STIG Demo Instances
    ec2: 
     access_key: "{{ ec2_access_key }}"
     secret_key: "{{ ec2_secret_key }}"
     keypair: "{{ ec2_keypair }}"
     group: "{{ ec2_security_group }}"
     type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     region: "{{ ec2_region }}"
     instance_tags: 
      ansible_group: justin-stig
      type: '{{ ec2_instance_type }}'
      group: '{{ ec2_security_group }}'
     exact_count: 0
     count_tag: 
      ansible_group: justin-stig
      type: '{{ ec2_instance_type }}'
      group: '{{ ec2_security_group }}'
     wait: false
    register: ec2
