---
# Create VLB
- hosts: all
  connection: local
  gather_facts: False

  vars_files:
  - pri_vars/all

  tasks:
  - name: Gather ec2 facts
    ec2_facts:  

  - name: Add hosts to ELB
    local_action:
      module: ec2_elb
      state: present
      region: "{{ ec2_region }}"
      ec2_elbs: "{{ app_name }}"
      instance_id: "{{ ec2_id }}"
