---
# Add Hosts to ELB
- hosts: all
  gather_facts: False

  tasks:
  - name: Gather ec2 facts
    ec2_facts:  
    register: facts

  - name: Add hosts to ELB
    local_action:
      module: ec2_elb
      state: present
      region: "{{ ec2_region }}"
      ec2_elbs: "{{ app_name }}"
      instance_id: "{{ hostvars[inventory_hostname]['ansible_facts']['instance-id'] }}"
